version: '3.5'

services: 
    postgres:
        container_name: contact-postgres
        image: postgres:12.5
        environment:
            - POSTGRES_DB=contact
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
        volumes:
            - ./database:/var/lib/postgresql/data
        networks:
            - postgresnetwork
            
    api:
        container_name: contact-api
        depends_on: [postgres]
        build:
            context: https://raw.githubusercontent.com/DMarlon/tact-api/master/Dockerfile
        working_dir: /api
        environment:
            - DB_SERVER=postgres
            - DB_PORT=5432
            - DB_NAME=contact
            - DB_USER=dev
            - DB_PASSWORD=dev
            - FRONT_SERVER=http://localhost:8801
        ports:
            - 8800:8080
        networks:
            - postgresnetwork

    front:
        container_name: contact-front
        build:
            context: https://raw.githubusercontent.com/DMarlon/tact-front/master/Dockerfile
            args:
                vue_app_front_name: Tact
                vue_app_api_url: http://localhost:8800
        working_dir: /front
        
        ports:
            - 8801:8801

    pgadmin:
        container_name: contact-pgadmin
        image: dpage/pgadmin4
        ports:
           - 8802:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=test@contact.com.br
            - PGADMIN_DEFAULT_PASSWORD=dev
        networks:
            - postgresnetwork

networks:
    postgresnetwork:
        driver: bridge
